# Generated by Django 3.1.5 on 2021-04-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=10, unique=True, verbose_name='닉네임')),
                ('realname', models.CharField(max_length=10, verbose_name='이름')),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여'), ('E', '기타'), ('X', '선택안함')], max_length=1, verbose_name='성별')),
                ('read_authority', models.IntegerField(default=1, verbose_name='읽기 권한')),
                ('write_authority', models.IntegerField(default=0, verbose_name='작성 권한')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='아바타')),
                ('user_category', models.CharField(choices=[('2014(1기)', '2014(1기)'), ('2015(2기)', '2015(2기)'), ('2016(3기)', '2016(3기)'), ('2017(4기)', '2017(4기)'), ('2018(5기)', '2018(5기)'), ('2019(6기)', '2019(6기)'), ('2020(7기)', '2020(7기)'), ('2021(8기)', '2021(8기)'), ('교직원', '교직원'), ('외부인', '외부인'), ('한아름', '한아름'), ('관리자', '관리자')], max_length=10, verbose_name='유저 카테고리')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is superuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-updated_at',),
            },
        ),
    ]
