# Generated by Django 3.1.9 on 2021-06-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.TextField(blank=True, default='', verbose_name='roles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.TextField(verbose_name='닉네임'),
        ),
    ]
