# Generated by Django 3.1.5 on 2021-04-23 14:12

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', django_summernote.fields.SummernoteTextField(verbose_name='내용')),
                ('anonymous_author', models.BooleanField(default=False, verbose_name='익명 여부')),
                ('status', models.CharField(choices=[('d', 'draft'), ('p', 'published'), ('t', 'trash')], default='p', max_length=2, verbose_name='게시글 공개 상태')),
                ('top_fixed', models.BooleanField(default=False, verbose_name='상단 고정 게시물')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 날짜')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='첨부파일')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='articles.article')),
            ],
        ),
    ]
