# Generated by Django 3.1.5 on 2021-02-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published'), ('t', 'trash')], default='p', max_length=2, verbose_name='게시글 공개 상태'),
        ),
    ]
