# Generated by Django 3.1.5 on 2021-02-27 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_board_default_board_format'),
        ('articles', '0003_auto_20210220_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='board.board', verbose_name='게시판'),
        ),
    ]
