# Generated by Django 3.1.5 on 2021-04-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210429_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislike_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='싫어요 수'),
        ),
        migrations.AddField(
            model_name='article',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='좋아요 수'),
        ),
    ]
