# Generated by Django 3.1.9 on 2021-06-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210430_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='viewed_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='조회수'),
        ),
    ]
