# Generated by Django 3.1.5 on 2021-04-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_top_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleattachment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='articles.article'),
        ),
    ]
