# Generated by Django 3.1.9 on 2021-06-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210610_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
    ]
