# Generated by Django 3.1.9 on 2021-06-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210613_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_restricted',
            field=models.BooleanField(default=False, verbose_name='댓글 작성 제한'),
        ),
    ]
