# Generated by Django 3.1.9 on 2021-06-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0002_auto_20210429_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': '해시태그', 'verbose_name_plural': '해시태그'},
        ),
    ]
