# Generated by Django 3.1.5 on 2021-01-31 18:07

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hanmaum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='인터뷰 제목')),
                ('interviewer', models.CharField(max_length=10, verbose_name='인터뷰어')),
                ('interviewee', models.CharField(max_length=10, verbose_name='인터뷰이')),
                ('content', django_summernote.fields.SummernoteTextField(verbose_name='내용')),
                ('thumnbail', models.ImageField(blank=True, null=True, upload_to='hanmaum/%Y/%m/%d', verbose_name='대표 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 시각')),
            ],
        ),
    ]
