# Generated by Django 3.1.5 on 2021-01-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanmaum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hanmaum',
            name='interviewee',
            field=models.CharField(default='', max_length=10, verbose_name='인터뷰이'),
        ),
        migrations.AlterField(
            model_name='hanmaum',
            name='interviewer',
            field=models.CharField(default='', max_length=10, verbose_name='인터뷰어'),
        ),
    ]
