# Generated by Django 3.1.5 on 2021-04-23 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hanmaum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hanmaumarticle',
            name='uploader',
            field=models.ForeignKey(db_column='uploader_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploader', to=settings.AUTH_USER_MODEL, verbose_name='업로더'),
        ),
    ]
