# Generated by Django 3.1.5 on 2021-02-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanmaum', '0002_auto_20210131_1816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hanmaum',
            new_name='HanmaumArticle',
        ),
    ]
