# Generated by Django 3.1.9 on 2021-05-31 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210430_2147'),
        ('hanmaum', '0003_auto_20210429_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hanmaumarticle',
            name='content',
        ),
        migrations.RemoveField(
            model_name='hanmaumarticle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hanmaumarticle',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='hanmaumarticle',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hanmaumarticle',
            name='status',
        ),
        migrations.RemoveField(
            model_name='hanmaumarticle',
            name='title',
        ),
        migrations.RemoveField(
            model_name='hanmaumarticle',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hanmaumarticle',
            name='uploader',
        ),
        migrations.AddField(
            model_name='hanmaumarticle',
            name='article_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hanmaumarticle',
            name='interviewee',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='인터뷰이'),
        ),
        migrations.AlterField(
            model_name='hanmaumarticle',
            name='interviewer',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='인터뷰어'),
        ),
        migrations.AlterField(
            model_name='hanmaumarticle',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', null=True, upload_to='hanmaum/%Y/%m/%d', verbose_name='대표 이미지'),
        ),
    ]
