# Generated by Django 3.1.9 on 2021-06-02 16:44

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hanmaum', '0004_auto_20210601_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hanmaumarticle',
            name='article_ptr',
        ),
        migrations.AddField(
            model_name='hanmaumarticle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hanmaumarticle',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='글쓴이'),
        ),
        migrations.AddField(
            model_name='hanmaumarticle',
            name='content',
            field=django_summernote.fields.SummernoteTextField(default=1, verbose_name='내용'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hanmaumarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='추가된 일시'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hanmaumarticle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제된 일시'),
        ),
        migrations.AddField(
            model_name='hanmaumarticle',
            name='dislike_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='싫어요 수'),
        ),
        migrations.AddField(
            model_name='hanmaumarticle',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='좋아요 수'),
        ),
        migrations.AddField(
            model_name='hanmaumarticle',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published'), ('t', 'trash')], default='p', max_length=2, verbose_name='게시글 공개 상태'),
        ),
        migrations.AddField(
            model_name='hanmaumarticle',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='제목'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hanmaumarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정된 일시'),
        ),
        migrations.AddField(
            model_name='hanmaumarticle',
            name='viewed_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='조회수'),
        ),
    ]
