# Generated by Django 3.1.5 on 2021-02-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanmaum', '0004_hanmaumarticle_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hanmaumarticle',
            old_name='thumnbail',
            new_name='thumbail',
        ),
    ]
