# Generated by Django 3.1.5 on 2021-02-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanmaum', '0005_auto_20210202_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hanmaumarticle',
            old_name='thumbail',
            new_name='thumbnail',
        ),
    ]
