# Generated by Django 3.1.9 on 2021-06-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanmaum', '0005_auto_20210603_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hanmaumarticle',
            options={'verbose_name': '한마음 게시글', 'verbose_name_plural': '한마음 게시글'},
        ),
    ]
