# Generated by Django 3.1.5 on 2021-04-23 14:12

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='제목')),
                ('content', django_summernote.fields.SummernoteTextField(verbose_name='내용')),
                ('top_fixed', models.BooleanField(default=False, verbose_name='상단 고정 게시물')),
                ('status', models.CharField(choices=[('d', 'draft'), ('p', 'published'), ('t', 'trash')], default='d', max_length=2, verbose_name='공지사항 공개 상태')),
                ('priority', models.IntegerField(default=0, verbose_name='우선순위')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 날짜')),
            ],
        ),
    ]
