# Generated by Django 3.1.9 on 2021-06-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_auto_20210429_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='viewed_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='조회수'),
        ),
    ]
