# Generated by Django 3.1.5 on 2021-04-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100, verbose_name='내용')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 시각')),
            ],
        ),
        migrations.CreateModel(
            name='MainBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, verbose_name='우선순위')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_board', to='boards.board', verbose_name='게시판')),
            ],
        ),
    ]
