# Generated by Django 3.1.5 on 2021-02-01 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210201_1501'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, verbose_name='우선순위')),
                ('visible_anonymous', models.BooleanField(default=True, verbose_name='비로그인 유저의 확인 가능 여부')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='board.board', verbose_name='게시판')),
            ],
        ),
    ]
