# Generated by Django 3.1.5 on 2021-02-28 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_board_visible_anonymous'),
        ('main', '0002_mainboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainboard',
            name='visible_anonymous',
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_board', to='board.board', verbose_name='게시판'),
        ),
    ]
