# Generated by Django 3.1.5 on 2021-02-06 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_model', models.CharField(default='', max_length=100, verbose_name='모델명')),
                ('activity_id', models.IntegerField(blank=True, null=True, verbose_name='객체 id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 날짜')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
        ),
        migrations.CreateModel(
            name='LikeActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='history.activity')),
                ('category', models.CharField(choices=[('like', '좋아요'), ('dislike', '싫어요')], max_length=10, null=True, verbose_name='카테고리')),
            ],
            bases=('history.activity',),
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_model', models.CharField(default='', max_length=100, verbose_name='모델명')),
                ('viewed_id', models.IntegerField(blank=True, null=True, verbose_name='객체 id')),
                ('viewed_count', models.IntegerField(default=0, verbose_name='유저별 조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 날짜')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
        ),
    ]
