# Generated by Django 3.1.5 on 2021-02-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeactivity',
            name='category',
            field=models.CharField(choices=[('like', '좋아요'), ('dislike', '싫어요'), ('none', '상태없음')], max_length=10, null=True, verbose_name='카테고리'),
        ),
    ]
