# Generated by Django 3.1.9 on 2021-06-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'verbose_name': '논문', 'verbose_name_plural': '논문'},
        ),
        migrations.AlterModelOptions(
            name='paperauthor',
            options={'verbose_name': '논문 저자', 'verbose_name_plural': '논문 저자'},
        ),
        migrations.AlterModelOptions(
            name='papercategory',
            options={'verbose_name': '논문 카테고리', 'verbose_name_plural': '논문 카테고리'},
        ),
        migrations.AlterModelOptions(
            name='paperversion',
            options={'verbose_name': '버전별 논문', 'verbose_name_plural': '버전별 논문'},
        ),
        migrations.AlterModelOptions(
            name='paperversionreviewer',
            options={'verbose_name': '버전별 논문 리뷰어', 'verbose_name_plural': '버전별 논문 리뷰어'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '리뷰', 'verbose_name_plural': '리뷰'},
        ),
    ]
