# Generated by Django 3.1.5 on 2021-02-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='top_fixed',
            field=models.BooleanField(default=False, verbose_name='상단 고정 게시물'),
        ),
    ]
