# Generated by Django 3.1.5 on 2021-02-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_top_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published'), ('t', 'trash')], default='d', max_length=2, verbose_name='공지사항 공개 상태'),
        ),
    ]
