# Generated by Django 3.1.5 on 2021-04-23 14:12

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='게시판명')),
                ('creator_category', models.CharField(choices=[('hanalum', '한아름'), ('user', '일반유저')], default='hanalum', max_length=8, verbose_name='게시판 제작자 분류')),
                ('auth_read', models.IntegerField(default=10, verbose_name='읽기 권한')),
                ('auth_write', models.IntegerField(default=10, verbose_name='쓰기 권한')),
                ('use_comment', models.BooleanField(default=True, verbose_name='댓글 사용 여부')),
                ('use_good', models.BooleanField(default=True, verbose_name='좋아요 사용 여부')),
                ('use_bad', models.BooleanField(default=True, verbose_name='싫어요 사용 여부')),
                ('use_anonymous', models.BooleanField(default=False, verbose_name='익명 사용 가능 여부')),
                ('status', models.CharField(choices=[('d', 'draft'), ('p', 'published'), ('t', 'trash')], default='d', max_length=2, verbose_name='게시판 공개 상태')),
                ('visible_anonymous', models.BooleanField(default=True, verbose_name='비로그인 유저의 확인 가능 여부')),
                ('default_article_format', django_summernote.fields.SummernoteTextField(default='', null=True, verbose_name='기본 작성 포맷')),
                ('board_format_category', models.CharField(choices=[('text', '텍스트 중심'), ('gallery', '이미지 중심')], default='text', max_length=10, verbose_name='게시판 기본 형태')),
                ('max_attachment_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='첨부 파일 최대 개수')),
            ],
        ),
        migrations.CreateModel(
            name='BoardAdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_notice_permission', models.BooleanField(default=True, verbose_name='게시판 내 공지 생성 권한')),
                ('delete_article_permission', models.BooleanField(default=False, verbose_name='게시글 삭제 권한')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='boards.board', verbose_name='게시판')),
            ],
        ),
    ]
