# Generated by Django 3.1.5 on 2021-04-23 14:25

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20210423_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='default_article_format',
            field=django_summernote.fields.SummernoteTextField(blank=True, default='', null=True, verbose_name='기본 작성 포맷'),
        ),
    ]
