# Generated by Django 3.1.5 on 2021-05-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20210429_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='우선순위'),
        ),
    ]
