# Generated by Django 3.1.9 on 2021-06-10 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0005_board_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='게시판 제작자'),
        ),
        migrations.AlterField(
            model_name='boardadminuser',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.board', verbose_name='게시판'),
        ),
        migrations.AlterField(
            model_name='boardadminuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='게시판 관리자'),
        ),
    ]
