# Generated by Django 3.1.9 on 2021-06-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20210613_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardadminuser',
            options={'verbose_name': '게시판 어드민 유저', 'verbose_name_plural': '게시판 어드민 유저'},
        ),
    ]
