# Generated by Django 3.1.9 on 2021-07-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20210613_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryBoard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('boards.board',),
        ),
        migrations.AddField(
            model_name='board',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='게시판 타입'),
        ),
    ]
