# Generated by Django 3.1.9 on 2021-07-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20210703_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalBoard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('boards.board',),
        ),
    ]
