# Generated by Django 3.1.9 on 2021-07-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    def set_default_board_type(apps, schema_editor):
        Board = apps.get_model("boards", "Board")
        for board in Board.objects.all():
            if not board.type:
                board.type = 'board'
                board.save()

    dependencies = [
        ('boards', '0011_auto_20210703_1752'),
    ]

    operations = [
        migrations.RunPython(set_default_board_type),
    ]
