# Generated by Django 3.1.5 on 2021-03-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published'), ('t', 'trash')], default='p', max_length=2, verbose_name='댓글 상태'),
        ),
    ]
