# Generated by Django 3.1.5 on 2021-02-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='게시판명')),
                ('auth_read', models.IntegerField(default=10, verbose_name='읽기 권한')),
                ('auth_write', models.IntegerField(default=10, verbose_name='쓰기 권한')),
                ('use_comment', models.BooleanField(default=True, verbose_name='댓글 사용 여부')),
                ('use_good', models.BooleanField(default=True, verbose_name='좋아요 사용 여부')),
                ('use_bad', models.BooleanField(default=True, verbose_name='싫어요 사용 여부')),
                ('use_anonymous', models.BooleanField(default=False, verbose_name='익명 게시판 여부')),
                ('status', models.CharField(default='d', max_length=2, verbose_name='게시판 공개 상태')),
            ],
        ),
    ]
