# Generated by Django 3.1.5 on 2021-02-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='use_anonymous',
            field=models.BooleanField(default=False, verbose_name='익명 사용 가능 여부'),
        ),
    ]
