# Generated by Django 3.1.5 on 2021-02-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210201_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'public'), ('t', 'trash')], default='d', max_length=2, verbose_name='게시판 공개 상태'),
        ),
    ]
