# Generated by Django 3.1.5 on 2021-02-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210201_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='max_attachment_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='첨부 파일 최대 개수'),
        ),
    ]
