# Generated by Django 3.1.5 on 2021-02-11 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0005_board_max_attachment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='게시판 제작자'),
        ),
        migrations.AddField(
            model_name='board',
            name='creator_category',
            field=models.CharField(choices=[('hanalum', '한아름'), ('user', '일반유저')], default='hanalum', max_length=8, verbose_name='게시판 제작자 분류'),
        ),
        migrations.CreateModel(
            name='BoardAdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_notice_permission', models.BooleanField(default=True, verbose_name='게시판 내 공지 생성 권한')),
                ('delete_article_permission', models.BooleanField(default=False, verbose_name='게시글 삭제 권한')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='board.board', verbose_name='게시판')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='게시판 관리자')),
            ],
        ),
    ]
