# Generated by Django 3.1.5 on 2021-02-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20210211_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='default_board_format',
            field=models.CharField(choices=[('text', '텍스트 중심'), ('gallery', '이미지 중심')], default='text', max_length=10, verbose_name='게시판 기본 형태'),
        ),
    ]
