# Generated by Django 3.1.5 on 2021-02-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_board_default_board_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='visible_anonymous',
            field=models.BooleanField(default=True, verbose_name='비로그인 유저의 확인 가능 여부'),
        ),
    ]
