# Generated by Django 3.1.5 on 2021-03-01 08:28

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20210301_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='default_article_format',
            field=django_summernote.fields.SummernoteTextField(null=True, verbose_name='기본 작성 포맷'),
        ),
    ]
