# Generated by Django 3.1.5 on 2021-03-03 11:13

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_board_default_article_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='default_article_format',
            field=django_summernote.fields.SummernoteTextField(default='', null=True, verbose_name='기본 작성 포맷'),
        ),
    ]
